plugin_version=0.6.14-dhw
org.gradle.jvmargs=-Xmx1024m
lombok_version=1.18.46
velocity_baseline_version=3.5.1
velocity_baseline_build=615
velocity_baseline_sha256=b4e3164df5377346854dc6cb9e6a78022b1946ff69e89676313f5f6f1c6f0fb3
velocity_baseline_url=https://fill-data.papermc.io/v1/objects/b4e3164df5377346854dc6cb9e6a78022b1946ff69e89676313f5f6f1c6f0fb3/velocity-3.5.1-615.jar
