plugins {
    id 'com.gradleup.shadow' version '9.1.0'
}


repositories {
    maven { url = 'https://repo.opencollab.dev/main' }
}

dependencies {
    compileOnly project(":api")
    compileOnly project(":flows")
    compileOnly 'org.geysermc.floodgate:api:2.2.2-SNAPSHOT'
    compileOnly 'org.geysermc.geyser:api:2.2.0-SNAPSHOT'

    testImplementation platform('org.junit:junit-bom:5.13.4')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation project(":api")
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}

shadowJar {
    archiveFileName = 'MultiLogin-Core.JarFile'
}

artifacts {
    archives shadowJar
}
